/* R69 — 🤖 Conversar com a I.A no Laboratório (estilo Claude, cérebro estético) */
const fs=require('fs'),path=require('path');
let ok=0,fail=0;const T=(n,c)=>{if(c){ok++;}else{fail++;console.log('  ✗ '+n);}};
const W=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const WK=fs.readFileSync(path.join(__dirname,'..','supabase','worker-live-backup.js'),'utf8');
const VJ=JSON.parse(fs.readFileSync(path.join(__dirname,'..','versao.json'),'utf8'));
T('1. item na barra do LAB (agora Fênix I.A)', /data-sview="ia" data-area="lab"/.test(W)&&W.includes('>Fênix I.A</button>'));
T('2. Relatórios continua no Lab', /data-sview="relatorios" data-area="lab"/.test(W));
T('3. handler do navStudio reabriu o chat', /sview==='ia'\)navigate\(\(\)=>\{state\.sview='ia';try\{renderIA\(\)\}catch/.test(W));
T('4. render no bloco do studio', /if\(state\.sview==='ia'\)renderIA\(\);else if\(state\.sview==='docs'\)/.test(W));
T('5. título Laboratório I.A · Fênix I.A', W.includes("'Laboratório I.A · Fênix I.A'"));
T('6. hero Fênix I.A', W.includes('<h3>Fênix I.A</h3>'));
T('7. nota do Lab menciona conversar', W.includes('converse com a inteligência artificial'));
T('8. chat usa o nosso worker (NUVEM_URL+/ia)', /NUVEM_URL\+'\/ia'/.test(W));
T('9. envia contexto da clínica + histórico', W.includes('buildIaCtx')&&/historico:hist/.test(W));
T('10. conversas sincronizadas (ia_conversas/ia_mensagens)', W.includes("table:'ia_conversas'")&&W.includes("table:'ia_mensagens'"));
T('11. badge de status Fênix I.A', W.includes("'Fênix I.A'"));
T('12. versão 1.6.49', W.includes("APP_VERSAO='1.6.70'"));
T('13. worker: cérebro estético (sem promessa médica)', WK.includes('NUNCA prometa resultado médico')&&WK.includes('limpeza de pele'));
T('14. worker: modos intactos (resumo + /ia-ok)', WK.includes("modo==='resumo'")&&WK.includes("'/ia-ok'"));
T('15. R66 intacto: resumo no relatório', /sc\[0\]==='resumo'\?relIaBloco\(\):''/.test(W));
T('16. R68 intacto: áreas do Studio', W.includes('id="sareaTgl"')&&W.includes('data-sarea="lab"'));
T('17. versao.json 1.6.49/R70', VJ.versao==='1.6.70'&&VJ.r==='R92'&&(VJ.melhorias||[]).length>=3);
T('18. JS válido', (()=>{try{new Function(W.match(/<script>([\s\S]*)<\/script>/)[1]);return true}catch(e){return false}})());
T('19. Center 2.0.0 intocado (UI nova da Plataforma)', fs.readFileSync(path.join(__dirname,'..','center-src','www','index.html'),'utf8').includes("CENTER_V='2.0.0'"));
console.log(fail?('FALHAS: '+fail):('TUDO OK ('+ok+'/19)'));
process.exit(fail?1:0);
