const fs=require('fs');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync('/home/user/tests/fenix-estetica.html','utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://fenix.test/',pretendToBeVisual:true});
const w=dom.window,d=w.document;const ev=s=>w.eval(s);
let pass=0,fail=0;
const ok=(c,l)=>{if(c){pass++;console.log('  ✔ '+l);}else{fail++;console.log('  ✘ FALHOU: '+l);}};
const navbtn=k=>[...d.querySelectorAll('#navStudio .navbtn')].find(b=>b.dataset.sview===k);
setTimeout(()=>{try{
ev(`entrarLocal({nome:'Clínica Teste'},'teste')`);
ev(`setMode('studio')`);
console.log('— Documentos abre a lista —');
navbtn('docs').click();
ok(ev(`state.sview`)==='docs','Clicar Documentos abre a LISTA');
ok(!d.getElementById('viewDocs').classList.contains('hidden'),'viewDocs visível');
console.log('— Editor de formulário → trocar seção —');
ev(`openFormEd(null)`);
ok(ev(`state.sview`)==='formEd','Dentro do editor de formulário');
navbtn('docs').click();
ok(ev(`state.sview`)==='docs'&&ev(`formDraft`)===null,'Documentos de DENTRO do editor (rascunho limpo)');
console.log('— Editor de documento → trocar seção —');
ev(`openDoc(null)`);
ok(ev(`state.sview`)==='doc','Dentro do editor de documento');
navbtn('forms').click();
ok(ev(`state.sview`)==='forms'&&ev(`state.docId`)===null,'Formulários de DENTRO do editor de documento');
navbtn('docs').click();
ok(ev(`state.sview`)==='docs','Volta pra Documentos');
console.log('— Respostas → trocar seção —');
ev(`setForm([{id:'fx',titulo:'F',descr:'',qs:[{id:'q1',tipo:'curto',texto:'P',opcoes:[],obr:false}],criadoEm:'',atualizadoEm:'',ts:1}])`);
ev(`openRespFill('fx')`);
navbtn('forms').click();
ok(ev(`state.sview`)==='forms'&&ev(`state.respForm`)===null,'Formulários a partir de preencher');
ev(`openRespList('fx')`);
navbtn('docs').click();
ok(ev(`state.sview`)==='docs'&&ev(`state.respId`)===null,'Documentos a partir da lista de respostas');
console.log('— Item ativo acompanha —');
navbtn('forms').click();
ok(navbtn('forms').classList.contains('active')&&!navbtn('docs').classList.contains('active'),'Formulários ativo');
navbtn('docs').click();
ok(navbtn('docs').classList.contains('active')&&!navbtn('forms').classList.contains('active'),'Documentos ativo');
ev(`openDoc(null)`);
ok(navbtn('docs').classList.contains('active'),'Editor mantém Documentos ativo');
console.log('\nRESULTADO: '+pass+' passaram, '+fail+' falharam');
process.exit(fail?1:0);
}catch(e){console.error('ERRO NO TESTE:',e);process.exit(2);}},300);
