
const fs=require('fs'),path=require('path');
const {JSDOM}=require(path.join('/home/user/tests','node_modules','jsdom'));
let html=fs.readFileSync('/home/user/index.html','utf-8');
const DBMENS=[];
html='<scr'+'ipt>window.supabase={createClient:function(){return {auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:function(){return{data:{unsubscribe:function(){}}}},signInWithPassword:async()=>({data:{user:{id:"u1",user_metadata:{nome:"Clinica Teste"}}},error:null}),signOut:async()=>{}},from:function(tb){return {select(){return this;},eq(){return this;},gt(){return this;},order(){return this;},limit(){return this;},async then(res){res({data:DBMENS.map(x=>Object.assign({},x)),error:null});},delete(){return {lt:async()=>({error:null})};},insert(r){DBMENS.push(Array.isArray(r)?r[0]:r);return {error:null};}};}};}};</scr'+'ipt>'+html;
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://geniterapeuta12-tech.github.io/fenix-estetica/index.html'});
const w=dom.window;w.DBMENS=DBMENS;
(async()=>{
await new Promise(r=>{if(w.document.readyState==='complete')return r();w.addEventListener('load',r);setTimeout(r,5000);});
const d=w.document;let falhas=0;const T=(n,c)=>{console.log((c?'  ✔ ':'  ✘ ')+n);if(!c)falhas++;};
w.eval("SB_TOKEN='t';CLINIC_ID='94133e7c';DB.usu=[{id:'1',nome:'Kaleb Santiago'},{id:'2',nome:'Maria Souza'}];try{localStorage.setItem('fenix_user_ativo',JSON.stringify({id:'x',nome:'Fatima Dono'}))}catch(e){}document.getElementById('authScreen').classList.add('hidden');document.getElementById('appScreen').classList.remove('hidden');document.getElementById('splash').classList.add('hidden');setMode('equipe');state.esub='msgs';renderApp();");
T('1. tela de msgs abre em tela cheia (chatwrap)', !!d.getElementById('chatWrap'));
const lis=d.querySelectorAll('#tgList li');
T('2. lista: 2 pessoas (sem eu mesmo; grupos aparecem à parte)', lis.length===2);
T('3. eu não apareço na lista', ![...lis].some(li=>li.textContent.includes('Fatima Dono')));
const liK=[...lis].find(li=>li.dataset.eqid==='Kaleb Santiago');liK.click();
await new Promise(r=>setTimeout(r,100));
T('4. cabeçalho mostra a pessoa', d.getElementById('tgNome').textContent==='Kaleb Santiago');
T('5. avatar tem cor própria (efeito na pessoa)', ((d.getElementById('tgAv').getAttribute('style')||d.getElementById('tgAv').style.cssText||'')).includes('background'));
T('6. conversa vazia → convite amigável', d.getElementById('tgArea').textContent.includes('Comece a conversa'));
d.getElementById('tgInput').value='Olá, Kaleb!';
d.getElementById('tgSend').click();
await new Promise(r=>setTimeout(r,150));
if(falhas===0||true)console.log('   [debug] peer=',w.eval('MSG.peer'),'· rows=',w.eval('MSG.rows.length'),'· tgMsg=',d.getElementById('tgMsg').textContent);
T('7. mensagem gravada na nuvem (1 row)', DBMENS.length===1 && DBMENS[0].texto==='Olá, Kaleb!');
T('8. bolha minha, dourada, com ✓✓', !!d.querySelector('#tgArea .tgb.me .ck'));
T('9. lista mostra prévia da msg', [...d.querySelectorAll('#tgList .tgprev')].some(p=>p.textContent.includes('Olá, Kaleb')));
const conteudo='x'.repeat(50000);
const f=new w.File([conteudo],'orcamento.txt',{type:'text/plain'});
Object.defineProperty(f,'size',{value:conteudo.length});
Object.defineProperty(d.getElementById('tgFile'),'files',{value:{0:f,length:1,item:()=>f},configurable:true});
d.getElementById('tgFile').dispatchEvent(new w.Event('change'));
await new Promise(r=>setTimeout(r,250));
T('10. anexo enviado (2 rows, com url data:)', DBMENS.length===2 && (DBMENS[1].url||'').startsWith('data:') && DBMENS[1].nome==='orcamento.txt');
T('11. cartão de arquivo na conversa', !!d.querySelector('#tgArea .chatfile') && d.querySelector('#tgArea .chatfile').textContent.includes('49 KB'));
const grande=new w.File(['y'],'grande.txt',{type:'text/plain'});
Object.defineProperty(grande,'size',{value:5*1048576});
Object.defineProperty(d.getElementById('tgFile'),'files',{value:{0:grande,length:1,item:()=>grande},configurable:true});
d.getElementById('tgFile').dispatchEvent(new w.Event('change'));
await new Promise(r=>setTimeout(r,250));
T('12. arquivo >1 MB recusado com aviso', d.getElementById('tgMsg').textContent.includes('muito pesado'));
DBMENS.push({id:'m9',clinic_id:'94133e7c',de:'Kaleb Santiago',para:'Fatima Dono',texto:'Oi! Já viu?',criado_em:'28/09/2026',ts:Date.now()});
await w.eval('msgPuxa()');
await new Promise(r=>setTimeout(r,150));
T('13. msg do outro lado aparece (bolha them)', !!d.querySelector('#tgArea .tgb.them') && d.querySelector('#tgArea .tgb.them').textContent.includes('Já viu'));
T('14. presença: "ativo agora" no cabeçalho', d.getElementById('tgStat').textContent==='ativo agora');
d.getElementById('tgBack').click();
T('15. voltar limpa conversa (mobile)', d.getElementById('tgArea').textContent.includes('Escolha alguém'));
T('16. rodapé avisa 24h + 5s', d.getElementById('chatWrap').textContent.includes('24h')&&d.getElementById('chatWrap').textContent.includes('5s'));
console.log(falhas? 'FALHAS: '+falhas : 'TUDO OK (16/16)');
process.exit(falhas?1:0);
})().catch(e=>{console.error('ERRO:',e.message);process.exit(1);});
