const fs=require('fs');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync('/home/user/tests/fenix-estetica.html','utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://fenix.test/',pretendToBeVisual:true});
const w=dom.window,d=w.document;
const ev=s=>w.eval(s);
const fire=(el,t)=>el.dispatchEvent(new w.Event(t,{bubbles:true}));
let pass=0,fail=0;
const ok=(c,l)=>{if(c){pass++;console.log('  ✔ '+l);}else{fail++;console.log('  ✘ FALHOU: '+l);}};

setTimeout(()=>{try{
console.log('— Formulário base (curta + longa + seletiva) —');
ev(`entrarLocal({nome:'Clínica Teste'},'teste')`);
ev(`setMode('studio')`);
[...d.querySelectorAll('#navStudio .navbtn')].find(b=>b.dataset.sview==='forms').click();
d.getElementById('btnNovoForm').click();
d.getElementById('formTitulo').value='Anamnese Facial';fire(d.getElementById('formTitulo'),'input');
const fab=d.getElementById('fabAddQ');
fab.click();
d.querySelector('.qcard:nth-of-type(1) .qtext').value='Qual seu nome?';fire(d.querySelector('.qcard:nth-of-type(1) .qtext'),'input');
d.querySelector('.qcard:nth-of-type(1) .req').click();
fab.click();
d.querySelector('.qcard:nth-of-type(2) .qtext').value='Histórico e queixas';fire(d.querySelector('.qcard:nth-of-type(2) .qtext'),'input');
d.querySelector('.qcard:nth-of-type(2) .qtypesel').value='longo';fire(d.querySelector('.qcard:nth-of-type(2) .qtypesel'),'change');
fab.click();
d.querySelector('.qcard:nth-of-type(3) .qtext').value='Tipo de pele';fire(d.querySelector('.qcard:nth-of-type(3) .qtext'),'input');
d.querySelector('.qcard:nth-of-type(3) .qtypesel').value='sel';fire(d.querySelector('.qcard:nth-of-type(3) .qtypesel'),'change');
let op=d.querySelector('[data-qopt="2"][data-j="0"]');op.value='Oleosa';fire(op,'input');
d.querySelector('[data-act="addopt"][data-i="2"]').click();
op=d.querySelector('[data-qopt="2"][data-j="1"]');op.value='Seca';fire(op,'input');
d.getElementById('btnFormSave').click();
ok(ev(`getForm().length`)===1,'Formulário com 3 tipos criado');
const FID=ev(`getForm()[0].id`);
d.getElementById('btnFormBack').click();

console.log('— Preencher na clínica: campos por tipo —');
const card=d.querySelector('#formList .clickable');
ok(card.textContent.includes('0 resposta(s)'),'Card com 0 respostas');
card.querySelector('[data-act="respfill"]').click();
ok(!d.getElementById('viewRespFill').classList.contains('hidden'),'Tela de preencher aberta');
ok(d.querySelectorAll('#respQsHost .qcard').length===3,'3 perguntas');
ok(!!d.querySelector('#respQsHost textarea.qtext'),'Longa = textarea');
ok(!!d.querySelector('#respQsHost select.qtext'),'Seletiva = dropdown');
ok([...d.querySelectorAll('#respQsHost select.qtext option')].some(o=>o.textContent==='Oleosa'),'Opções no dropdown');
d.getElementById('btnRespSave').click();
ok(d.getElementById('respMsg').textContent.includes('nome'),'Sem nome → erro');
d.getElementById('respPessoa').value='Maria Silva';
d.getElementById('btnRespSave').click();
ok(d.getElementById('respMsg').textContent.includes('obrigatória'),'Obrigatória vazia → erro');
const ins=d.querySelectorAll('#respQsHost [data-qid]');
ins[0].value='Maria da Silva';
ins[1].value='Queixas de acne há 2 anos';
ins[2].value='Oleosa';
d.getElementById('btnRespSave').click();
ok(!d.getElementById('viewRespList').classList.contains('hidden'),'Salvo → lista de respostas');
ok(ev(`getResp().length`)===1&&JSON.parse(w.localStorage.getItem('fk_resp_teste')).length===1,'Persistida (sync → formulario_respostas)');

console.log('— Ver resposta —');
d.querySelector('#respList .clickable[data-rid]').click();
ok(d.getElementById('respViewTitle').textContent==='Maria Silva','Nome no detalhe');
const ans=[...d.querySelectorAll('#respViewHost .answ')];
ok(ans.length===3&&ans[0].textContent==='Maria da Silva'&&ans[2].textContent==='Oleosa','Respostas corretas');
d.getElementById('btnRespViewBack').click();

console.log('— Duplicada bloqueada —');
[...d.querySelectorAll('#navStudio .navbtn')].find(b=>b.dataset.sview==='forms').click();
d.querySelector('[data-act="respfill"]').click();
d.getElementById('respPessoa').value='maria silva';
d.querySelector('#respQsHost [data-qid]').value='x';
d.getElementById('btnRespSave').click();
ok(d.getElementById('respMsg').textContent.includes('já respondeu'),'Mesma pessoa bloqueada');
ok(ev(`getResp().length`)===1,'Nada duplicado');
d.getElementById('btnRespBack').click();

console.log('— Segunda pessoa + exclusão + contagem —');
[...d.querySelectorAll('#navStudio .navbtn')].find(b=>b.dataset.sview==='forms').click();
d.querySelector('[data-act="respfill"]').click();
d.getElementById('respPessoa').value='João Pedro';
const ins2=d.querySelectorAll('#respQsHost [data-qid]');
ins2[0].value='João';ins2[2].value='Seca';
d.getElementById('btnRespSave').click();
ok(ev(`getResp().length`)===2&&d.getElementById('respListCount').textContent==='2 resposta(s)','2 respostas');
const del=d.querySelector('[data-act="delresp"]');del.click();del.click();
ok(ev(`getResp().length`)===1,'Exclusão ok');
[...d.querySelectorAll('#navStudio .navbtn')].find(b=>b.dataset.sview==='forms').click();
ok(d.querySelector('#formList .clickable').textContent.includes('1 resposta(s)'),'Card com 1 resposta(s)');
console.log('— Backup —');
ok(Object.keys(ev(`snapshotData()`)).includes('resp'),'snapshotData contém resp');
console.log('\nRESULTADO: '+pass+' passaram, '+fail+' falharam');
process.exit(fail?1:0);
}catch(e){console.error('ERRO NO TESTE:',e);process.exit(2);}},300);
