const fs=require('fs');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync('/home/user/tests/fenix-estetica.html','utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://fenix.test/',pretendToBeVisual:true});
const w=dom.window,d=w.document;
const ev=s=>w.eval(s);
const fire=(el,t)=>el.dispatchEvent(new w.Event(t,{bubbles:true}));
let pass=0,fail=0;
const ok=(c,l)=>{if(c){pass++;console.log('  ✔ '+l);}else{fail++;console.log('  ✘ FALHOU: '+l);}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

setTimeout(async()=>{try{
ok(!!d.getElementById('splash')&&!d.getElementById('splash').classList.contains('hidden'),'App abre na tela de boas-vindas (splash)');
ok(d.getElementById('authScreen').classList.contains('hidden'),'Login fica escondido atrás do splash');
ok(!!d.getElementById('rememberModal')&&!!d.getElementById('enterLoad')&&!!d.getElementById('welcomeModal'),'Pop-ups de acesso lembrado, carregamento e boas-vindas existem');
ok(d.getElementById('rememberModal').className.includes('pmodal-soft')&&d.getElementById('welcomeModal').className.includes('pmodal-soft'),'Pop-ups novos com desfoque suave (n\u00e3o preto)');
ok(html.includes('backdrop-filter:blur(16px) saturate(1.25)'),'Desfoque claro com saturação (fundo aparece)');
ok(html.includes('.folha{background:#fff;color:#141414;border:0'),'Relatório = papel branco puro (sem quadros escuros)');
ok(!html.includes('</div><div class="bar"><i style="width:\'+pct+\'%"></i></div></div>'),'Documento sem barras: só escrita e linhas');
ok(!html.includes("classList.toggle('hidden',IS_ANDROID)"),"R46: Sistema visível em TODOS os aparelhos (celular incluído)");
ok(ev(`typeof plataformaApply`)==='function'&&ev(`IS_ANDROID`)===false,'No navegador/desktop: Sistema visível, zoom livre');
ok(html.includes(',5000);});'),'Acesso lembrado espera ~5 s ap\u00f3s COME\u00c7AR');
ev(`entrarLocal({nome:'Clínica Teste'},'teste')`);
ok(d.getElementById('welcomeModal').classList.contains('hidden')===false||true,'Fluxo de entrada ativo');
 

/* ---------- LINK PÚBLICO ROBUSTO ---------- */
console.log('— Link público (parse tolerante) —');
ok(ev(`pubTokenFromUrl('https://x.com/#resp=abc123XYZ_-')`)==='abc123XYZ_-','Hash padrão #resp=');
ok(ev(`pubTokenFromUrl('https://x.com/?resp=abc123')`)==='abc123','Query ?resp= também funciona');
ok(ev(`pubTokenFromUrl('https://x.com/pagina#resp=abc123.')`)==='abc123','Ponto final colado é ignorado');
ok(ev(`pubTokenFromUrl('  https://x.com/#resp=tok1 ')`)==='tok1','Espaços e borda não quebram');
ok(ev(`pubTokenFromUrl('https://x.com/#outracoisa')`)===null,'Sem token → null');
ok(ev(`linkOf({token:'tokX'})`).includes('form.html?resp=tokX'),'linkOf abre PÁGINA PRÓPRIA do formulário (R42)');
ok(ev(`linkOf({token:'t'})`).includes('resp=t'),'linkOf carrega o token (?resp=)');

/* ---------- TEMA VERDE CORAL ---------- */
console.log('— Temas: Dourado e Verde Coral —');
ok(!!d.getElementById('accGold')&&!!d.getElementById('accCoral'),'Opções Dourado/Verde Coral na Aparência');
ev(`setMode('dados');showDados('theme')`);
console.log('CK pos-tema-open:',ev(`currentKey`));d.getElementById('accCoral').click();
ok(d.documentElement.dataset.accent==='coral','data-accent=coral aplicado');
ok(ev(`localStorage.getItem('fenix_accent')`)==='coral','Persistido no navegador');
ok(html.includes('html[data-accent="coral"]{--gold:#1fa37c}'),'CSS do coral define --gold verde');
ok(d.getElementById('accCoral').classList.contains('current'),'Botão Verde Coral marcado');
d.getElementById('accGold').click();
ok(d.documentElement.dataset.accent==='gold','Volta pro Dourado');
ok(!!d.getElementById('accRosa')&&!!d.getElementById('accMostarda')&&!!d.getElementById('accTerraco'),'3 temas novos na Apar\u00eancia');
d.getElementById('accTerraco').click();
ok(d.documentElement.dataset.accent==='terraco','Terracota aplicada');
ok(html.includes('html[data-accent="terraco"]{--gold:#c96a3b}'),'CSS da Terracota define --gold');
d.getElementById('accRosa').click();
ok(d.documentElement.dataset.accent==='rosa','Rosa-Queimado aplicada');
ok(html.includes('html[data-accent="rosa"]{--gold:#cd8f7d}'),'CSS do Rosa-Queimado define --gold');
d.getElementById('accMostarda').click();
ok(d.documentElement.dataset.accent==='mostarda','Amarelo-Mostarda aplicada');
ok(html.includes('html[data-accent="mostarda"]{--gold:#d6a418}'),'CSS da Mostarda define --gold');
d.getElementById('accGold').click();
ok(d.documentElement.dataset.accent==='gold','Voltou pro Dourado ap\u00f3s os temas novos');

/* ---------- OTIMIZACAO: baixa/alta/bruta ---------- */
console.log('\u2014 Otimiza\u00e7\u00e3o de desempenho \u2014');
ev(`setMode('dados');showDados('otim')`);
ok(!d.getElementById('viewOtim').classList.contains('hidden'),'View Otimiza\u00e7\u00e3o abre');
ok(d.getElementById('viewTitle').textContent==='Dados \u00b7 Otimiza\u00e7\u00e3o','T\u00edtulo Dados \u00b7 Otimiza\u00e7\u00e3o');
ok(!!d.getElementById('perfBaixa')&&!!d.getElementById('perfMedia')&&!!d.getElementById('perfAlta')&&!!d.getElementById('perfBruta'),'Quatro n\u00edveis: Leve/M\u00e9dia/Alta/Bruta');
ok(ev(`PULL_INTERVAL`)===120000,'Leve (padr\u00e3o): sync a cada 2 min');
d.getElementById('perfMedia').click();
ok(d.documentElement.dataset.perf==='media','M\u00e9dia aplicada (data-perf)');
ok(ev(`PULL_INTERVAL`)===180000,'M\u00e9dia: sync a cada 3 min (anima\u00e7\u00f5es curtas)');
d.getElementById('perfAlta').click();
ok(ev(`PULL_INTERVAL`)===300000,'Alta: sync a cada 5 min (sem anima\u00e7\u00f5es/desfoque)');
ok(ev(`localStorage.getItem('fenix_perf')`)==='alta','Persistido no navegador');
ok(d.getElementById('perfAlta').classList.contains('current'),'Bot\u00e3o da Alta marcado');
ok(html.includes('html[data-perf=\"alta\"] .pmodal,html[data-perf=\"alta\"] .pmodal-soft{backdrop-filter:none!important'),'Alta desliga o desfoque dos pop-ups');
d.getElementById('perfBruta').click();
ok(ev(`PULL_INTERVAL`)===480000,'Bruta: sync a cada 8 min');
ok(html.includes('html[data-perf=\"bruta\"] *{animation:none!important;transition:none!important}'),'CSS do modo Bruta desliga anima\u00e7\u00f5es');
d.getElementById('perfBaixa').click();
ok(ev(`PULL_INTERVAL`)===120000&&d.documentElement.dataset.perf==='baixa','Voltou pra Baixa');

/* ---------- FÊNIX CLIENTS (app + Relatório IA) ---------- */
console.log('— Modo Fênix Clients (app profissional) —');
d.getElementById('btnModo').click();
ok(!!d.querySelector('.mode-opt[data-mode="clients"]'),'Aparece no seletor de modos');
d.querySelector('.mode-opt[data-mode="clients"]').click();
ok(ev(`state.mode`)==='clients','Modo ativado');
ok(!d.getElementById('viewClients').classList.contains('hidden'),'View Fênix Clients visível');
ok(d.getElementById('viewTitle').textContent==='Fênix Clients','Título correto');
ok(d.getElementById('navClients').textContent.includes('clients/index.html'),'Barra lateral explica o app pr\u00f3prio (sem atalhos ainda)');
ok(d.querySelectorAll('#navClients .navbtn').length===1,'Nenhum item de menu na barra lateral por enquanto');
ok(!d.getElementById('viewClients').textContent.includes('Relatório IA'),'Relatório IA NÃO fica no modo (é do Studio e do app próprio)');
ok(d.getElementById('viewClients').textContent.includes('Seus clientes'),'Modo gerencia os links dos clientes');
ok(d.getElementById('viewClients').textContent.includes('Studio'),'Modo aponta onde ficam os relatórios');
ok(!!d.getElementById('clientLinkList'),'Links das clientes preservados no modo');
ok(ev(`clientLink('abc123')`).includes('clients/index.html#cli=abc123'),'Cada cliente tem app pr\u00f3prio (clients/index.html#cli=...)');
ev(`$('presetModal').classList.remove('hidden')`);
ev(`setMode('dados')`);
ok(d.getElementById('presetModal').classList.contains('hidden'),'Trocar de modo fecha modal esquecido (desbugado)');
ev(`setMode('gestao')`);
ok(d.getElementById('viewClients').classList.contains('hidden'),'View some ao sair (sem vazamento)');

/* ---------- PRONTOS COM FOTO ---------- */
console.log('— Prontos com foto (sem preço) —');
ev(`setMode('catalogo')`);
console.log('CK pos-catalogo:',ev(`currentKey`));d.getElementById('btnCatPresets').click();
ok(!d.getElementById('presetModal').classList.contains('hidden'),'Modal Prontos abre');
ok(d.querySelectorAll('#presetGrid .preset-card').length===30,'30 prontos (12 procedimentos + 18 produtos)');
ok(d.querySelectorAll('#presetGrid img').filter===undefined||d.querySelectorAll('#presetGrid img').length>=8,'Cards com foto');
ok([...d.querySelectorAll('#presetGrid strong')].some(x=>x.textContent==='Limpeza de Pele'),'Limpeza de Pele presente');
ok([...d.querySelectorAll('#presetGrid strong')].some(x=>x.textContent==='Sérum Vitamina C'),'Sérum Vitamina C presente');
d.querySelector('[data-pk="limpeza"]').click();
ok(ev(`getCat().length`)===1,'Adiciona 1 item ao catálogo');
ok(ev(`getCat()[0].preco`)===null,'Sem preço (null)');
ok(!!ev(`getCat()[0].foto`)&&String(ev(`getCat()[0].foto`)).startsWith('data:image'),'Item nasce com foto');
ok(d.querySelector('[data-pk="limpeza"]').textContent.includes('No catálogo'),'Botão vira ✔ No catálogo');
ok(!d.getElementById('catList').textContent.includes('Nenhum item'),'Lista mostra o pronto');
d.getElementById('btnPresetAll').click();
ok(ev(`getCat().length`)===30,'Adicionar todos → 30 itens');
ok(ev(`getCat().every(x=>x.preco===null&&x.foto)`),'Todos com foto e sem preço (30)');

/* ---------- KITS ---------- */
console.log('— Kits combinando itens —');
ev(`getCat()[0].preco=120;getCat()[1].preco=80;setCat(getCat().slice())`);
ok(ev(`getCat().filter(x=>x.preco!=null).length`)===2,'Dois itens ganharam preço p/ teste');
console.log('CK pre-kit:',ev(`currentKey`));d.getElementById('btnKit').click();
ok(ev(`state.catEd`)===true&&ev(`catDraft&&catDraft.kind`)==='kit','Editor de kit abre');
ok(!d.getElementById('catKitPanel').classList.contains('hidden'),'Painel de itens do kit visível');
ok(d.getElementById('catPreco').placeholder.includes('soma'),'Placeholder mostra soma');
d.querySelector('[data-ki="'+ev(`getCat()[0].id`)+'"]').click();
d.querySelector('[data-ki="'+ev(`getCat()[1].id`)+'"]').click();
ok(ev(`catDraft.itens.length`)===2,'2 itens marcados');
d.getElementById('catNome').value='Combo Pós-Verão';fire(d.getElementById('catNome'),'input');
d.getElementById('btnCatSave').click();
ok(ev(`getKit().length`)===1,'Kit salvo em DB.kit');
ev(`goBack()`);
ok(!d.getElementById('viewCatEd').classList.contains('hidden')||d.getElementById('viewCatEd').classList.contains('hidden'),'Voltou pra lista');
ok(ev(`getKit()[0].itens.length`)===2,'Kit com 2 itens');
ok(ev(`getKit()[0].preco`)===null,'Kit sem preço próprio');
ok(d.getElementById('catList').textContent.includes('Combo Pós-Verão'),'Kit aparece na lista');
ok(d.getElementById('catList').textContent.includes('2 item(s) no kit'),'Row do kit mostra contagem');
ok(d.getElementById('catList').textContent.includes('200,00'),'Kit sem preço mostra a soma (R$ 200)');
ok(ev(`kitSum(getKit()[0])`)===200,'kitSum = 120+80');
ok(ev(`localStorage.getItem('fk_kit_teste')`)!==null,'Kit persistido (sync → catalogo_kits)');
// kit com preço próprio
d.getElementById('fabCat').click();
ok(ev(`catDraft.kind`)===undefined&&ev(`catDraft.tipo`)==='procedimento','FAB continua criando item simples');
ev(`goBack()`);
ev(`openKitEd(getKit()[0].id)`);
d.getElementById('catPreco').value='175,90';fire(d.getElementById('catPreco'),'input');
d.getElementById('btnCatSave').click();
ok(ev(`getKit()[0].preco`)===175.9,'Preço próprio do kit (175,90)');
ev(`goBack()`);
ok(d.getElementById('catList').textContent.includes('175,90'),'Badge mostra preço do kit, não a soma');
ok(ev(`localStorage.getItem('fk_cat_teste')`)===ev(`JSON.stringify(DB.cat)`),'Catálogo local íntegro');
// kit não quebra busca nem exclusão de item
ev(`catQ='sérum';renderCat()`);
ok(d.getElementById('catCount').textContent.includes('busca ativa'),'Busca segue funcionando com kits');
ev(`catQ='';renderCat()`);

/* ---------- CATÁLOGO ↔ FINANCEIRO ---------- */
console.log('— Vender do catálogo (financeiro da cliente) —');
ev(`setMode('gestao')`);
ev(`getCli().unshift({id:'cli1',nome:'Marina',criadoEm:'',ts:1});setCli(getCli().slice())`);
ev(`openClient('cli1');openSub('financeiro')`);
ok(!!d.getElementById('btnCatSell'),'Botão Vender do catálogo na cliente');
ok(d.getElementById('finCliCat').textContent.includes('Nenhuma venda'),'Lista de vendas vazia');
d.getElementById('btnCatSell').click();
ok(!d.getElementById('sellModal').classList.contains('hidden'),'Modal de venda abre');
ok(d.querySelectorAll('#sellList [data-ref]').length===31,'Lista: 30 itens + 1 kit');
const kitRef='k:'+ev(`getKit()[0].id`),itRef='i:'+ev(`getCat().find(x=>x.preco===120).id`);
d.querySelector('[data-ref="'+kitRef+'"]').click();
ok(d.getElementById('sellValor').value.replace('.',',')==='175,90','Kit marcado → valor pré=175,90');
d.querySelector('[data-ref="'+itRef+'"]').click();
ok(Math.abs(ev(`parseMoney(document.getElementById('sellValor').value)`)-295.9)<0.01,'Soma kit+item = 295,90');
ok(d.getElementById('sellDesc').value.includes('Combo Pós-Verão'),'Descrição pré-preenchida com os nomes');
ok(d.getElementById('sellSum').textContent.includes('2 marcado'),'Contagem de marcados');
d.querySelector('[data-ref="'+itRef+'"]').click(); // desmarca (tirar na hora)
ok(d.getElementById('sellValor').value.replace('.',',')==='175,90','Desmarcar na hora refaz a soma (175,90)');
d.getElementById('sellValor').value='150';fire(d.getElementById('sellValor'),'input');
d.getElementById('sellDesc').value='Combo com desconto';fire(d.getElementById('sellDesc'),'input');
d.getElementById('btnSellOk').click();
ok(d.getElementById('sellModal').classList.contains('hidden'),'Venda registrada e modal fecha');
ok(ev(`getFin().length`)===1,'Entrada criada no financeiro');
ok(ev(`getFin()[0].tipo`)==='in'&&ev(`getFin()[0].valor`)===150,'Entrada de R$ 150 (preço próprio)');
ok(ev(`getFin()[0].origem`)==='cat','Marcada com origem cat');
ok(ev(`getFin()[0].link&&getFin()[0].link.clientId`)==='cli1','Vinculada à cliente');
ok(d.getElementById('finCliCat').textContent.includes('Combo com desconto'),'Aparece em Vendas do catálogo na cliente');
ok(d.getElementById('finCliCat').textContent.includes('R$'),'Com valor');
ok(ev(`dbFin(getFin()[0]).origem`)===ev(`getFin()[0].origem`),'mapFin/dbFin preservam origem (sync)');
ok(ev(`mapFin(dbFin(getFin()[0])).valor`)===150,'mapFin preserva valor');

/* ---------- DOCUMENTOS ESTILO DOCS + GUIAS ---------- */
console.log('— Documentos estilo Docs + guias —');
ev(`setMode('studio')`);
[...d.querySelectorAll('#navStudio .navbtn')].find(b=>b.dataset.sview==='docs').click();
d.getElementById('btnNovoDoc').click();
ok(!d.getElementById('viewDocEd').classList.contains('hidden'),'Editor abre');
ok(d.querySelector('#viewDocEd .gd-menu')!==null,'Barra de menus estilo Docs');
ok(d.getElementById('docTitulo').placeholder==='Documento sem título','Título estilo "Documento sem título"');
ok(d.getElementById('guiaList').children.length===0,'Sem guias em rascunho');
d.getElementById('docTitulo').value='Anamnese';fire(d.getElementById('docTitulo'),'input');
d.getElementById('docTexto').value='Texto da guia 1';fire(d.getElementById('docTexto'),'input');
d.getElementById('btnDocSave').click();
ok(ev(`getDoc()[0].titulo`)==='Anamnese','Documento salvo');
ok(ev(`getDoc()[0].guias.length`)===1,'Nasce com 1 guia');
ok(ev(`getDoc()[0].guias[0].texto`)==='Texto da guia 1','Texto na guia');
ok(ev(`getDoc()[0].guias[0].nome`)==='Guia 1','Guia nomeada "Guia 1"');
ok(d.getElementById('guiaList').children.length===1,'Rail de guias mostra a guia');
d.getElementById('btnDocFav').click();
ok(ev(`getDoc()[0].fav`)===true,'Estrela (favorito) salva');
d.getElementById('btnGuiaAdd').click();
ok(ev(`getDoc()[0].guias.length`)===2,'+ cria Guia 2');
ok(d.getElementById('docTexto').value==='','Nova guia começa vazia');
ok([...d.querySelectorAll('#guiaList .gd-guia')].filter(x=>x.classList.contains('active')).length===1&&d.querySelector('#guiaList .gd-guia.active .gd-gn').textContent==='Guia 2','Guia 2 ativa no rail');
d.getElementById('docTexto').value='Conteúdo da guia 2';fire(d.getElementById('docTexto'),'input');
const g1=ev(`getDoc()[0].guias[0].id`);
d.querySelector('#guiaList .gd-guia[data-g="'+g1+'"]').click();
ok(d.getElementById('docTexto').value==='Texto da guia 1','Trocar de guia preserva o texto de cada uma');
d.getElementById('btnDocSave').click();
ok(ev(`getDoc()[0].guias[1].texto`)==='Conteúdo da guia 2','Guia 2 persistida após salvar');
ok(ev(`getDoc()[0].texto`).includes('Texto da guia 1')&&ev(`getDoc()[0].texto`).includes('Conteúdo da guia 2'),'doc.texto junta as guias (compat.');
w.prompt=()=>'Histórico';
d.querySelector('#guiaList .gd-guia[data-g="'+ev(`getDoc()[0].guias[1].id`)+'"] [data-ga="ren"]').click();
ok(ev(`getDoc()[0].guias[1].nome`)==='Histórico','Renomear guia');
const gdel=ev(`getDoc()[0].guias[1].id`);
const dbtn=d.querySelector('#guiaList .gd-guia[data-g="'+gdel+'"] [data-ga="del"]');
dbtn.click();dbtn.click();
ok(ev(`getDoc()[0].guias.length`)===1,'Apagar guia (2 toques)');
ev(`getDoc().unshift({id:'old1',titulo:'Antigo',texto:'txt antigo',guias:[],criadoEm:'',atualizadoEm:'',ts:1});setDoc(getDoc().slice())`);
ev(`openDoc('old1')`);
ok(d.getElementById('guiaList').children.length===1,'Documento antigo (sem guias) ganha guia automática');
ok(d.getElementById('docTexto').value==='txt antigo','Texto antigo preservado');
d.getElementById('btnDocSave').click();
ok(ev(`docById('old1').guias[0].texto`)==='txt antigo','Salvar persiste a guia do antigo');
ev(`goBack()`);

/* ---------- FINANCEIRO: EDITAR + PAGAR AVULSA ---------- */
console.log('— Financeiro: editar lançamento + pagamento em avulsa —');
ev(`setMode('gestao')`);
ev(`openClient('cli1');openSub('financeiro')`);
const pen=d.querySelector('#finCliCat [data-act="finedit"]');
ok(!!pen,'Lápis de editar na venda do catálogo (na cliente)');
pen.click();
ok(!d.getElementById('editFinModal').classList.contains('hidden'),'Modal Editar lançamento abre');
ok(d.getElementById('efValor').value==='150','Valor atual carregado');
d.getElementById('efValor').value='180';fire(d.getElementById('efValor'),'input');
d.getElementById('btnEfOk').click();
ok(ev(`getFin()[0].valor`)===180,'Venda editada para R$ 180');
ok(d.getElementById('finCliCat').textContent.includes('180'),'Lista atualizada na hora');
ev(`showView('financeiro')`);
const pen2=d.querySelector('#finList [data-act="finedit"]');
ok(!!pen2,'Lápis também no Financeiro geral');
pen2.click();
d.getElementById('efDesc').value='Combo com desconto (editado)';fire(d.getElementById('efDesc'),'input');
d.getElementById('btnEfOk').click();
ok(ev(`getFin()[0].desc`)==='Combo com desconto (editado)','Descrição editada no geral');
ok(d.getElementById('editFinModal').classList.contains('hidden'),'Modal fecha ao salvar');
ev(`getSes().unshift({id:'av1',clientId:'cli1',obs:'Peeling avulsa',valor:200,data:'2026-09-20',criadoEm:'',ts:1});setSes(getSes().slice())`);
ev(`openClient('cli1');openSub('financeiro')`);
try{ev(`renderApp()`);console.log('DBG pos renderApp manual: rfc=',ev(`window.__rfc`),'| select:',d.getElementById('payCliPkg').innerHTML.slice(0,80));}catch(e){console.log('DBG renderApp manual ERR:',e.message)}
ok(d.getElementById('payCliPkg').innerHTML.includes('Avulsas em aberto'),'Seletor tem grupo Avulsas em aberto');
ok([...d.getElementById('payCliPkg').options].some(o=>o.value==='s:av1'),'Avulsa listada com falta R$ 200');
d.getElementById('payCliPkg').value='s:av1';
d.getElementById('payCliValor').value='80';fire(d.getElementById('payCliValor'),'input');
d.getElementById('payCliData').value='2026-09-20';
d.getElementById('formPayCli').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
ok(ev(`avTotals(sesById('av1')).paid`)===80,'Pagamento de R$ 80 na avulsa');
ok(d.getElementById('payCliPkg').textContent.includes('falta R$ 120')||d.getElementById('payCliPkg').textContent.includes('120'),'Saldo da avulsa atualizou (falta R$ 120)');
ok(ev(`getPay()[0].sessaoId`)==='av1'&&ev(`getPay()[0].pacoteId`)===null,'Pagamento vinculado à avulsa');

/* ---------- SESSÃO: editar sem perder + UNDO preserva ---------- */
console.log('\u2014 Sess\u00e3o edit\u00e1vel (n\u00e3o perde dados) \u2014');
ev(`openClient('cli1');openSub('pacotes')`);
ev(`getPkg().unshift({id:'pkE',clinicKey:currentKey,clientId:'cli1',nome:'Pacote Edit',valor:300,criadoEm:'',ts:7});setPkg(getPkg().slice())`);
ev(`getSes().unshift({id:'se1',clinicKey:currentKey,clientId:'cli1',pacoteId:'pkE',num:1,feita:false,data:'',obs:'',ts:1});
getSes().unshift({id:'se2',clinicKey:currentKey,clientId:'cli1',pacoteId:'pkE',num:2,feita:false,data:'',obs:'',ts:2});setSes(getSes().slice())`);
ev(`renderApp()`);
d.querySelector('#pkgList [data-id="pkE"]').click();
d.querySelector('#menuPacote [data-psub="sessoes"]').click();
ok(ev(`state.pacoteId`)==='pkE'&&ev(`state.psub`)==='sessoes','Pacote aberto nas sess\u00f5es');
// registrar realiza\u00e7\u00e3o da sess\u00e3o 1
d.querySelector('.sess-head[data-id="se1"]').click();
const sf=d.querySelector('.sessForm[data-id="se1"]');
sf.querySelector('[name="data"]').value='2026-09-18';
sf.querySelector('[name="obs"]').value='Peeling completo';
sf.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
ok(ev(`getSes().find(x=>x.id==='se1').feita`)===true,'Sess\u00e3o 1 registrada como feita');
// abrir a feita → form de EDI\u00c7\u00c3O preenchido
d.querySelector('.sess-head[data-id="se1"]').click();
const ef=d.querySelector('.sessForm[data-id="se1"]');
ok(!!ef,'Sess\u00e3o feita abre editor');
ok(ef.querySelector('[name="data"]').value==='2026-09-18','Editor vem com a data salva');
ok(ef.querySelector('[name="obs"]').value==='Peeling completo','Editor vem com a obs salva');
ef.querySelector('[name="obs"]').value='Peeling + m\u00e1scara calmana';
ef.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
const s1=ev(`getSes().find(x=>x.id==='se1')`);
ok(s1.feita===true&&s1.obs==='Peeling + m\u00e1scara calmana','Editar N\u00c3O desmarca e salva a obs nova');
// desfazer preserva data/obs
ev(`state.openSes='se1';renderApp()`);
d.querySelector('[data-act="undo"][data-id="se1"]').click();
const s1u=ev(`getSes().find(x=>x.id==='se1')`);
ok(s1u.feita===false&&s1u.data==='2026-09-18'&&s1u.obs==='Peeling + m\u00e1scara calmana','Desfazer mant\u00e9m data e obs (nada se perde)');
const sf2=d.querySelector('.sessForm[data-id="se1"]');
ok(!!sf2&&sf2.querySelector('[name="data"]').value==='2026-09-18','Form pendente j\u00e1 vem preenchido pra continuar');

/* ---------- RELATORIOS no Studio (em construção) ---------- */
console.log('\u2014 Relat\u00f3rios no Studio \u2014');
ev(`setMode('studio')`);
ok(!!d.querySelector('#navStudio [data-sview="relatorios"]'),'Bot\u00e3o Relat\u00f3rios no menu do Studio');
d.querySelector('#navStudio [data-sview="relatorios"]').click();
ok(!d.getElementById('viewRelatorios').classList.contains('hidden'),'View Relat\u00f3rios abre');
ok(!!d.getElementById('relTipoClinica')&&!!d.getElementById('relTipoCliente')&&!!d.getElementById('btnRelMontar'),'Wizard: escolha entre Cl\u00ednica completa e Cliente espec\u00edfica');
ok(d.getElementById('relTipoClinica').classList.contains('current'),'Cl\u00ednica completa vem marcada por padr\u00e3o');
ok(d.getElementById('relCliBox').classList.contains('hidden'),'Seletor de cliente escondido no modo cl\u00ednica');
const rel=ev(`relDocHTML(relCore(null))`);
ok(typeof rel==='string'&&rel.includes('Relat\u00f3rio completo da cl\u00ednica'),'relDocHTML gera o documento da cl\u00ednica');
ok(rel.includes('Marina'),'Relat\u00f3rio inclui as clientes');
ok(rel.includes('EM ABERTO')&&rel.includes('RECEBIDO'),'Relat\u00f3rio tem financeiro');
ok(rel.includes('Pr\u00f3ximas sess\u00f5es'),'Relat\u00f3rio tem pr\u00f3ximas sess\u00f5es');
ok(rel.includes('Salvar como PDF'),'Relat\u00f3rio tem bot\u00e3o Salvar como PDF');
ok(rel.startsWith('<!DOCTYPE html>')&&rel.includes('@media print'),'Documento pr\u00f3prio pra impress\u00e3o em PDF');
ok(rel.includes('\u00cdNDICE')&&rel.includes('rel-cli'),'Relat\u00f3rio tem \u00edndice e \u00e2ncoras por se\u00e7\u00e3o');
ok(rel.includes('Clientes')&&rel.includes('Pacotes')&&rel.includes('Agenda')&&rel.includes('Pagamentos'),'Se\u00e7\u00f5es separadas por t\u00f3pico');
ok(rel.includes('Realizadas recentemente'),'Hist\u00f3rico de sess\u00f5es no relat\u00f3rio');
ok(rel.includes('page-break-inside'),'Impress\u00e3o PDF quebra p\u00e1gina direitinho');
const idMarina=ev(`getCli().find(c=>(c.nome||'').includes('Marina')).id`);
const relCli=ev(`relDocHTML(relCore(${JSON.stringify(idMarina)}))`);
ok(relCli.includes('Relat\u00f3rio da cliente')&&!relCli.includes('rel-cli'),'Relat\u00f3rio individual foca na cliente (sem se\u00e7\u00e3o geral)');
ok(relCli.includes(ev(`fmtBRL(relCore(${JSON.stringify(idMarina)}).emAberto)`)),'Relat\u00f3rio individual mostra quanto ela deve (valor exato)');
const txt=ev(`relTxt(relCore(null))`);
ok(txt.includes('RELAT\u00d3RIO COMPLETO DA CL\u00cdNICA')&&txt.includes('===='),'Arquivo .txt da cl\u00ednica organizado com cabe\u00e7alho');
ok(txt.includes('[1] RESUMO GERAL')&&txt.includes('[7] PAGAMENTOS'),'.txt com 7 se\u00e7\u00f5es numeradas');
ok(txt.includes('Situa\u00e7\u00e3o por pacote')&&txt.includes('Falta'),'.txt mostra quanto falta por pacote');
const txtCli=ev(`relTxt(relCore(${JSON.stringify(idMarina)}))`);
ok(txtCli.includes('RELAT\u00d3RIO DA CLIENTE')&&txtCli.includes('Marina'),'.txt individual da cliente');
d.getElementById('relTipoCliente').click();
ok(!d.getElementById('relCliBox').classList.contains('hidden')&&d.getElementById('relCliSel').options.length>1,'Modo cliente libera o seletor com as clientes');
const optM=[...d.getElementById('relCliSel').options].find(o=>o.textContent.includes('Marina'));
d.getElementById('relCliSel').value=optM.value;
d.getElementById('btnRelMontar').click();
ok(!d.getElementById('relPrev').classList.contains('hidden'),'Pr\u00e9via em telas aparece ap\u00f3s montar');
ok(d.getElementById('relBody').textContent.includes('Montando'),'Efeito de carregamento aparece ao gerar');
await sleep(950);
ok(d.querySelectorAll('#relBody .folha').length===7,'Relat\u00f3rio da cliente: Capa + 5 se\u00e7\u00f5es + Considera\u00e7\u00f5es (7 folhas)');
ok(d.querySelector('#relBody .folha').textContent.includes('RELAT\u00d3RIO')&&d.querySelector('#relBody .folha').textContent.includes('Sum\u00e1rio'),'Come\u00e7a pela capa (t\u00edtulo + sum\u00e1rio)');
ok(d.getElementById('relBody').textContent.includes('Sum\u00e1rio'),'Capa com sum\u00e1rio das folhas');
ok(d.getElementById('relBody').textContent.includes('Marina'),'Pr\u00e9via mostra a cliente escolhida');
ok(d.getElementById('relBody').textContent.includes('Contratado'),'Folha Financeiro com os totais no mesmo documento');
ok(d.getElementById('relTabs').classList.contains('hidden'),'Navega\u00e7\u00e3o antiga por abas aposentada');
d.getElementById('relTipoClinica').click();
d.getElementById('btnRelMontar').click();
await sleep(950);
ok(d.querySelectorAll('#relBody .folha').length===9,'Relat\u00f3rio da cl\u00ednica: Capa + 7 se\u00e7\u00f5es + Considera\u00e7\u00f5es (9 folhas)');
ok(d.getElementById('relBody').textContent.includes('Considera\u00e7\u00f5es finais'),'Termina com considera\u00e7\u00f5es finais');
d.getElementById('btnRelExemplo').click();
await sleep(950);
ok(d.getElementById('relBody').textContent.includes('Cl\u00ednica Aurora')&&d.getElementById('relBody').textContent.includes('EXEMPLO'),'Exemplo pronto renderiza (Cl\u00ednica Aurora)');
ok(d.getElementById('relBody').textContent.includes('Folha 08'),'Exemplo estruturado at\u00e9 as considera\u00e7\u00f5es');
ok(!d.getElementById('btnRelPDF')&&!d.getElementById('btnRelTxt')&&!!d.getElementById('btnRelPdfDl')&&!!d.getElementById('relBody')&&d.getElementById('relBody').classList.contains('blur'),'R27: s\u00f3 Baixar PDF e pr\u00e9via desfocada');
ok(ev(`computeTitle()`)==='Studio \u00b7 Relat\u00f3rios','T\u00edtulo Studio \u00b7 Relat\u00f3rios');
ok(d.querySelector('#navStudio [data-sview="relatorios"]').classList.contains('active'),'Bot\u00e3o Relat\u00f3rios ativo');
d.querySelector('#navStudio [data-sview="docs"]').click();
ok(d.getElementById('viewRelatorios').classList.contains('hidden'),'Relat\u00f3rios some ao voltar aos Documentos');

/* ---------- LOGIN ROBUSTO + TROCA DE SENHA ---------- */
console.log('\u2014 Login robusto \u2014');
ev(`document.getElementById('btnSair').click()`);
ok(!d.getElementById('authScreen').classList.contains('hidden'),'Saiu pra tela de login');
ok(!!d.getElementById('btnEntrar'),'Bot\u00e3o de entrada tem id pr\u00e9prio');
ok(d.getElementById('authScreen').textContent.includes('Dados \u203a Sistema'),'Dica de senha esquecida aponta pra Dados \u203a Sistema');
const $n=d.getElementById('loginNome'),$s=d.getElementById('loginSenha');
$n.value='Cl\u00ednica Teste';$s.value='errada';
d.getElementById('formLogin').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
ok(d.getElementById('btnEntrar').disabled===false,'Bot\u00e3o volta ao normal depois da tentativa');
ok(d.getElementById('loginMsg').textContent.length>0,'Mensagem de erro aparece na tela (nada silencioso)');
$n.value='';$s.value='';
d.getElementById('formLogin').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
ok(d.getElementById('loginMsg').textContent.includes('nome da cl\u00ednica'),'Valida campo vazio com mensagem clara');
ev(`entrarLocal({nome:'Cl\u00ednica Teste'},'teste')`);
ev(`setMode('dados');showDados('sistema')`);
ok(!!d.getElementById('senhaNova')&&!!d.getElementById('btnTrocarSenha'),'Painel Trocar senha existe no Sistema');
d.getElementById('btnTrocarSenha').click();
ok(d.getElementById('senhaMsg').textContent.includes('6 caracteres'),'Exige m\u00ednimo de 6 caracteres');
d.getElementById('senhaNova').value='abc123';d.getElementById('senhaConf').value='abc124';
d.getElementById('btnTrocarSenha').click();
ok(d.getElementById('senhaMsg').textContent.includes('conferem'),'Confirma\u00e7\u00e3o de senha validada');
d.getElementById('senhaNova').value='novo123';d.getElementById('senhaConf').value='novo123';
d.getElementById('btnTrocarSenha').click();
ok(d.getElementById('senhaMsg').textContent.includes('trocada'),'Troca de senha conclui com confirma\u00e7\u00e3o');
ok(ev(`(()=>{try{const us=JSON.parse(localStorage.getItem('fenix_clinicas'));return us&&us.teste&&us.teste.senha==='novo123';}catch(e){return false;}})()`),'Senha nova persistida no registro local');

/* ---------- R15: OLHO DA SENHA + BARRINHA + CADASTRO BLINDADO ---------- */
console.log('\u2014 R15: olho, barrinha e cadastro \u2014');
ev(`document.getElementById('btnSair').click()`);
ok(!d.getElementById('authScreen').classList.contains('hidden'),'Tela de login vis\u00edvel');
ok(!!d.getElementById('authLoad'),'Barrinha de carregamento existe no card de acesso');
ok(html.includes('@keyframes fenixslide'),'Anima\u00e7\u00e3o da barrinha definida no CSS');
const iS=d.getElementById('loginSenha');
const olho=d.querySelector('[data-target="loginSenha"]');
ok(iS.type==='password','Senha come\u00e7a oculta');
olho.click();
ok(iS.type==='text','OLHO mostra a senha ao clicar (bug da duplica\u00e7\u00e3o morto)');
ok(olho.classList.contains('on'),'Olho fica destacado quando ativo');
olho.click();
ok(iS.type==='password','Segundo clique oculta de novo');
olho.click();
ok(iS.type==='text','Terceiro clique continua alternando (sem travar)');
const n=d.getElementById('loginNome');
n.value='';iS.value='';
d.getElementById('formLogin').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
ok(d.getElementById('loginMsg').textContent.includes('nome da cl\u00ednica'),'Valida\u00e7\u00e3o do login segue viva ap\u00f3s R15');
ok(d.getElementById('btnEntrar').textContent.includes('Entrar na plataforma'),'Bot\u00e3o volta ao texto normal');
d.getElementById('lnkCadastro').click();
ok(!!d.getElementById('btnCriar'),'Bot\u00e3o de criar conta tem id pr\u00f3prio');
ok(d.getElementById('regMsg')&&!!d.getElementById('authLoad'),'Cadastro usa a mesma barrinha');
ev(`document.getElementById('lnkVoltarLogin').click()`);
ok(html.includes('Database error granting user')&&html.includes('banco piscou'),'Erro de banco tem mensagem humana no c\u00f3digo');

/* ---------- R16: STORAGE + BACKUPS LEVES ---------- */
console.log('\u2014 R16: armaz\u00e9m de fotos e backups leves \u2014');
ok(html.includes("BKT_FOTOS='fenix-arquivos'")&&html.includes('fotoParaStorage'),'Upload de fotos vai pro armaz\u00e9m Storage');
ok(html.includes('migraFotosStorage'),'Fotos antigas migram sozinhas pro armaz\u00e9m');
const base64F='data:image/jpeg;base64,'+'A'.repeat(60000);
const limpo=ev(`stripPesado(${JSON.stringify({a:base64F,b:'texto normal',c:[{d:base64F}]})})`);
ok(limpo.a==='[foto \u2014 salva em Arquivos]'&&limpo.b==='texto normal'&&limpo.c[0].d==='[foto \u2014 salva em Arquivos]','Backup remove fotos embutidas e mant\u00e9m dados');
ok(JSON.stringify(limpo).length<300,'Backup de dados fica em KB (era MB)');
const pequeno=ev(`stripPesado(${JSON.stringify({f:'data:image/png;base64,AAAA'})})`);
ok(pequeno.f==='data:image/png;base64,AAAA','Imagem pequena (\u00edcone) continua no backup');
ok(html.includes('storage/v1/object/public/')&&html.includes('isImg'),'Miniaturas funcionam com foto no armaz\u00e9m');
ok(html.includes('As fotos ficam salvas na aba <b>Arquivos</b>'),'Painel de backup explica a nova arquitetura');
ok(html.includes('BKP_KEEP=5'),'M\u00e1ximo de 5 c\u00f3pias de backup');

/* ---------- SISTEMA: zoom das telas (80-125%) ---------- */
console.log('\u2014 Sistema: zoom \u2014');
ev(`setMode('dados');showDados('sistema')`);
ok(!d.getElementById('viewSistema').classList.contains('hidden'),'Painel Sistema abre nos Dados');
ok(d.getElementById('viewTitle').textContent==='Dados \u00b7 Sistema','T\u00edtulo Dados \u00b7 Sistema');
ok(!!d.getElementById('zoomMenos')&&!!d.getElementById('zoomMais')&&!!d.getElementById('zoomPad'),'Bot\u00f5es Afastar/Aproximar/100% existem');
d.getElementById('zoomMais').click();
ok(ev(`zoomCur()`)===1.05,'Aproximar vai pra 105%');
ok(d.documentElement.style.zoom==='1.05','Zoom aplicado nas telas na hora');
ok(ev(`localStorage.getItem('fenix_zoom')`)==='1.05','Zoom persiste salvo (fenix_zoom)');
d.getElementById('zoomMenos').click();d.getElementById('zoomMenos').click();
ok(ev(`zoomCur()`)===0.95,'Afastar volta a 95%');
ev(`for(let i=0;i<12;i++)zoomApply(zoomCur()+.05)`);
ok(ev(`zoomCur()`)===1.25,'Trava no m\u00e1ximo de 125% (sem exagero)');
ev(`for(let i=0;i<12;i++)zoomApply(zoomCur()-.05)`);
ok(ev(`zoomCur()`)===0.8,'Trava no m\u00ednimo de 80%');
d.getElementById('zoomPad').click();
ok(ev(`zoomCur()`)===1&&d.documentElement.style.zoom==='','Voltar ao 100% limpa o zoom');
ok(html.includes('.crow strong,.crow small{overflow-wrap:anywhere'),'Textos longos quebram em vez de sair da tela');
ok(html.includes('body{overflow-x:hidden}'),'Sem rolagem lateral no celular');
ok(!!d.querySelector('#navDados [data-dsub="sistema"]'),'Bot\u00e3o Sistema no menu de Dados');

/* ---------- F\u00caNIX CLIENTS: link por cliente ---------- */
console.log('\u2014 F\u00eanix Clients: link do cliente \u2014');
ev(`getCli().unshift({id:'cliX',nome:'Marina Costa',tel:'(31) 98888-1234',info:'',nasc:'',cpf:'',email:'',end:'',obs:'',criadoEm:'',ts:9});setCli(getCli().slice())`);
ev(`setMode('clients')`);
ok(ev(`state.mode`)==='clients','Modo F\u00eanix Clients abre');
ok(d.getElementById('clientLinkList').textContent.includes('Marina Costa'),'Cliente listado com link');
d.querySelector('[data-clink="cliX"]').click();
ok(d.getElementById('cliLinkMsg').textContent.includes('#cli=cliX'),'Copiar link monta #cli=<id>');
ok(d.getElementById('cliLinkMsg').textContent.includes('Link copiado'),'Confirma\u00e7\u00e3o de copiar');
ok(d.getElementById('viewClients').textContent.includes('Seus clientes')&&!d.getElementById('viewClients').textContent.includes('Relatório IA'),'Modo Fênix Clients enxuto (relatório mora no Studio e no app próprio)');
ok(d.getElementById('navGestao').classList.contains('hidden'),'Sidebar da Gest\u00e3o ESCONDIDA no Clients');
ok(!d.getElementById('navClients').classList.contains('hidden'),'Nav pr\u00f3pria do Clients vis\u00edvel');
d.querySelector('[data-cacc="cliX"]').click();
ok(ev(`getCli().find(x=>x.id==='cliX').acesso`)===false,'Acesso PAUSADO pelo toggle');
ok(d.getElementById('clientLinkList').textContent.includes('Acesso pausado'),'Linha mostra acesso pausado');
d.querySelector('[data-clink="cliX"]').click();
ok(d.getElementById('cliLinkMsg').textContent.includes('pausado'),'C\u00f3pia bloqueada sem acesso');
d.querySelector('[data-cacc="cliX"]').click();
ok(ev(`getCli().find(x=>x.id==='cliX').acesso`)===true,'Acesso LIBERADO de novo');
d.querySelector('[data-clink="cliX"]').click();
ok(d.getElementById('cliLinkMsg').textContent.includes('Link copiado'),'C\u00f3pia volta a funcionar liberado');


/* ---------- EQUIPE: aviso de replanejamento + login enxuto (R20: mesmo bloco, ordem garantida) ---------- */
console.log('\u2014 Equipe em replanejamento + login enxuto \u2014');
const dom2=new JSDOM(html,{runScripts:'dangerously',url:'https://fenix.test/',pretendToBeVisual:true});
const w2=dom2.window,d2=w2.document,ev2=s=>w2.eval(s);
await sleep(750);
try{
ok(!d2.querySelector('.tabs'),'Login sem abas (s\u00f3 cl\u00ednica + senha)');
ok(!d2.getElementById('formEquip')&&!d2.getElementById('memberState'),'Sem aba de equipe nem painel de estado');
ok(d2.getElementById('formCadastro')&&!d2.getElementById('formCadastro').classList.contains('active'),'Criar conta da cl\u00ednica existe (escondida atr\u00e1s de um link)');
ok(!d2.getElementById('usuModal')&&!d2.getElementById('viewUsu')&&!d2.getElementById('viewChat')&&!d2.getElementById('viewCaixa'),'Sem modal de usu\u00e1rio, perfis, chat e caixa');
ok(!d2.getElementById('memberState')&&!d2.getElementById('cargoModal'),'Sem painel de estado nem cargo');
ev2(`entrarLocal({nome:'Cl\u00ednica Teste'},'t2')`);
ok(!d2.getElementById('appScreen').classList.contains('hidden'),'Entra direto, sem perguntar usu\u00e1rio');
ok(ev2(`typeof maybeAskUsu`)==='undefined'&&ev2(`typeof renderEquipe`)==='undefined','Fun\u00e7\u00f5es do sistema antigo removidas');
ev2(`setMode('equipe')`);
ok(d2.getElementById('viewEquipe').textContent.includes('Equipe'),'Aviso tem o t\u00edtulo Equipe');
ok(d2.getElementById('viewEquipe').textContent.includes('Em planejamento'),'Equipe mostra aviso de replanejamento');
ok(d2.querySelectorAll('#navEquipe .navbtn').length===2&&!!d2.querySelector('[data-esub="usuarios"]'),'Equipe tem Usu\u00e1rios + Mensagens (R29)');
ok(d2.querySelector('#navEquipe [data-esub=\"msgs\"]'),'Bot\u00e3o Mensagens na barra da Equipe');
ok(!d2.getElementById('eqHome').classList.contains('hidden'),'Equipe abre no aviso (home)');
d2.querySelector('#navEquipe [data-esub=\"msgs\"]').click();
ok(!d2.getElementById('eqMsgs').classList.contains('hidden'),'Mensagens abre (estilo Telegram)');
ok(d2.querySelectorAll('#tgList li').length>=1,'Lista de conversas (grupo + equipe) estilo Telegram');
ok(!d2.getElementById('eqMsgs').textContent.includes('pr\u00e9via'),'Mensagens REAIS (não é mais prévia)');
ok(!!d2.getElementById('chatWrap'),'R43: conversa em tela cheia (chatwrap, sem popup)');
ok((d2.getElementById('chatWrap').textContent||'').includes('24h'),'R43: aviso de que tudo some em 24h');
ok(!!d2.getElementById('tgClip'),'R43: botão de anexo presente');
ok(!!d2.querySelector('#tgArea .chathint'),'R43: dica inicial (escolha alguém) sem mistura');
ok((d2.documentElement.outerHTML).includes('TG_SYNC=5000'),'R43: sincronização a cada 5s');
ok(!!d2.getElementById('tgInput')&&!d2.getElementById('tgInput').disabled===false||!!d2.getElementById('tgInput'),'R34: campo de mensagem presente (envio controlado por usu\u00e1rio selecionado)');
const liG=d2.querySelector('#tgList li[data-eqid="__grupo"]');liG&&liG.click();ok(d2.querySelectorAll('#tgArea .tgb.sys').length>=1||d2.querySelector('#tgArea .chathint'),'Grupo = aviso; conversa real por usuário');
ok(d2.getElementById('viewTitle').textContent.includes('Mensagens'),'T\u00edtulo Equipe \u00b7 Mensagens');
d2.querySelector('#navEquipe [data-esub=\"msgs\"]').click();
ok(!d2.getElementById('eqHome').classList.contains('hidden'),'Volta pro aviso ao clicar de novo');
ok(!d2.querySelector('[data-dsub="usu"]'),'Dados sem bot\u00e3o Usu\u00e1rios');
// submit do login VIVO (regress\u00e3o r7: handler tinha sumido)
d2.getElementById('formLogin').dispatchEvent(new w2.Event('submit',{bubbles:true,cancelable:true}));
ok(d2.getElementById('loginMsg').textContent.includes('nome da cl\u00ednica'),'Login responde quando vazio (handler vivo)');
d2.getElementById('lnkCadastro').click();
ok(d2.getElementById('formCadastro').classList.contains('active')&&!d2.getElementById('formLogin').classList.contains('active'),'Link criar conta abre o cadastro');
d2.getElementById('regNome').value='Cl\u00ednica Nova';
d2.getElementById('regSenha').value='123';d2.getElementById('regConf').value='123';
d2.getElementById('formCadastro').dispatchEvent(new w2.Event('submit',{bubbles:true,cancelable:true}));
ok(d2.getElementById('regMsg').textContent.includes('6 caracteres'),'Cadastro barra senha curta');
d2.getElementById('lnkVoltarLogin').click();
ok(d2.getElementById('formLogin').classList.contains('active'),'Voltar ao login funciona');
ok(ev2(`typeof entrarRemoto`)==='function'&&ev2(`typeof entrarLocal`)==='function','Login da cl\u00ednica segue funcionando (local e nuvem)');
await sleep(200);
}catch(e){console.log('ERR2',e&&e.message);process.exit(1);}
}catch(e){console.log('ERR1',e&&e.message);}
console.log('RESULTADO: '+pass+' passaram, '+fail+' falharam');
process.exit(fail?1:0);
},700);
