/* R68 — ÁREAS no Studio: 🎓 Studio | 🧪 Laboratório I.A (Relatórios mora no Lab) */
const fs=require('fs'),path=require('path');
let ok=0,fail=0;const T=(n,c)=>{if(c){ok++;}else{fail++;console.log('  ✗ '+n);}};
const W=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const VJ=JSON.parse(fs.readFileSync(path.join(__dirname,'..','versao.json'),'utf8'));
T('1. alternador de área existe (sareaTgl)', W.includes('id="sareaTgl"'));
T('2. botões 🎓 Studio e 🧪 Laboratório I.A', W.includes('data-sarea="studio"')&&W.includes('data-sarea="lab"'));
T('3. Relatórios marcado como área LAB', /data-sview="relatorios" data-area="lab"/.test(W));
T('4. Documentos/Formulários/Planilha na área STUDIO', /data-sview="docs" data-area="studio"/.test(W)&&/data-sview="forms" data-area="studio"/.test(W)&&/data-sview="planilha" data-area="studio"/.test(W));
T('5. pintaSarea esconde itens da outra área', /b\.style\.display=\(b\.dataset\.area===state\.sarea\)\?'':'none'/.test(W));
T('6. clicar na área Lab abre Relatórios', /state\.sarea=b\.dataset\.sarea;[\s\S]{0,160}state\.sview='relatorios'/.test(W));
T('7. clicar na área Studio abre Documentos', /else navigate\(\(\)=>\{state\.sview='docs'/.test(W));
T('8. área salva no localStorage (fenix_sarea)', W.includes("localStorage.setItem('fenix_sarea'")&&W.includes("localStorage.getItem('fenix_sarea')"));
T('9. renderApp pinta a área no Studio', /if\(studio\)\{\s*try\{pintaSarea\(\)\}catch/.test(W));
T('10. título: Laboratório I.A · Relatórios', W.includes("'Laboratório I.A · Relatórios'"));
T('11. nota da barra muda por área', W.includes('Laboratório I.A: converse com a inteligência artificial'));
T('12. clicar num item sincroniza a área (data-area)', /const ar=b\.dataset\.area;if\(ar&&ar!==state\.sarea\)/.test(W));
T('13. CSS das áreas (areatoggle/areabtn.on)', W.includes('.areatoggle{')&&W.includes('.areabtn.on{'));
T('14. versão 1.6.49', W.includes("APP_VERSAO='1.6.84'"));
T('15. Resumo da I.A no relatório intacto (R66)', /sc\[0\]==='resumo'\?relIaBloco\(\):''/.test(W));
T('16. versao.json 1.6.49/R70', VJ.versao==='1.6.84'&&VJ.r==='R110'&&(VJ.melhorias||[]).length>=3);
T('17. JS válido', (()=>{try{new Function(W.match(/<script>([\s\S]*)<\/script>/)[1]);return true}catch(e){return false}})());
T('18. Center 2.0.0 intocado (UI nova da Plataforma)', fs.readFileSync(path.join(__dirname,'..','center-src','www','index.html'),'utf8').includes("CENTER_V='2.4.0'"));
console.log(fail?('FALHAS: '+fail):('TUDO OK ('+ok+'/18)'));
process.exit(fail?1:0);
