/* teste_r55 — RETOOLADO R92: agora testa a CENTER v2.0 (Plataforma Fênix) no lugar da UI clássica (arquivada no git @ b775e51) */
const fs=require('fs'),path=require('path');
const {JSDOM}=require(path.join('/home/user/tests','node_modules','jsdom'));
let falhas=0;const T=(n,c)=>{console.log((c?'  ✔ ':'  ✘ ')+n);if(!c)falhas++;};
const html=fs.readFileSync(path.join('/home/user','center-src','www','index.html'),'utf-8');
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://geniterapeuta12-tech.github.io/fenix-estetica/center/app.html',pretendToBeVisual:true});
const {window}=dom;const d=window.document;
T('1. é a CENTER v2.0 (Plataforma Fênix)', html.includes("CENTER_V='2.0.0'")&&!!d.querySelector('.marca')&&d.querySelector('.marca').textContent.includes('Center'));
T('2. login: email + senha + botão Entrar (conta Fênix)', !!d.getElementById('fxEmail')&&!!d.getElementById('fxSenha')&&!!d.getElementById('btnEntrar'));
T('3. auto-atualização viva (checaUiNova + nunca rebaixa)', html.includes('async function checaUiNova')&&html.includes('setInterval(checaUiNova,30*60*1000)')&&html.includes('function uiMaisNova'));
T('4. base href injetado no swap (ícones resolvem)', html.includes('<base href="https://geniterapeuta12-tech.github.io/fenix-estetica/center/">'));
T('5. byte-idêntica à publicada em center/app.html', fs.readFileSync(path.join('/home/user','center','app.html'),'utf-8')===html);
T('6. painel DONO: criar conta (email/senha/nome/papel) presente', !!d.getElementById('vDono')&&!!d.getElementById('ncEmail')&&!!d.getElementById('ncSenha')&&!!d.getElementById('ncPapel'));
T('7. painel DONO: bloquear via lista (render por data-blk)', html.includes('[data-blk]')&&html.includes("'/auth-fenix/bloquear'"));
T('8. painel CLÍNICA: «Abrir o Estética já logado» + app instalado', !!d.getElementById('btnAbrirLogado')&&!!d.getElementById('btnAbrirApp2'));
T('9. convite: modal 1-uso com app (fenix://) · navegador (?fx=) · copiar', !!d.getElementById('conviteW')&&html.includes("'fenix://abrir?token='+encodeURIComponent(t)")&&html.includes("PAGES+'?fx='")&&!!d.getElementById('btnConvCopy'));
T('10. endpoints corretos (login · confere · abrir · lista · criar · bloquear)', ['/auth-fenix/login','/auth-fenix/confere?token=','/auth-fenix/abrir','/auth-fenix/lista','/auth-fenix/criar-conta','/auth-fenix/bloquear'].every(p=>html.includes(p)));
T('11. sessão guardada c/ fallback (fenix_center_fx + _mem)', html.includes('fenix_center_fx')&&html.includes('function lsSet(k,v)'));
T('12. UI papel+terracota+serifa (cara Claude)', html.includes('--papel:#FAF9F5')&&html.includes('--terra:#D97757')&&html.includes("Georgia,'Times New Roman',serif"));
T('13. sem service worker (Center é app) e sem chave no cliente', !html.includes('serviceWorker.register')&&!/sk_|cfut_|ghp_/i.test(html));
T('14. JS da Center executa sem erro (jsdom carregou os painéis)', (()=>{try{return !!(d.getElementById('vLogin')&&d.getElementById('vDono')&&d.getElementById('vCli'))}catch(e){return false}})());
console.log(falhas?('FALHAS: '+falhas):'TUDO OK (14/14)');
process.exit(falhas?1:0);
